# Generated by Django 3.0.8 on 2020-07-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_difficult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficult',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
