# Generated by Django 3.0.8 on 2020-07-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_category_difficult_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
