# Generated by Django 3.0.8 on 2020-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorect_answer_0', models.CharField(max_length=50)),
                ('incorect_answer_1', models.CharField(max_length=50)),
                ('incorect_answer_2', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
