# Generated by Django 3.0.8 on 2020-07-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficult',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorect_answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Difficult',
        ),
        migrations.DeleteModel(
            name='IncorectAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
