# Generated by Django 3.0.8 on 2020-07-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0010_auto_20200720_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('corect_answer', models.CharField(max_length=50)),
                ('incorect_answer_0', models.CharField(max_length=50)),
                ('incorect_answer_1', models.CharField(max_length=50)),
                ('incorect_answer_2', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Category')),
                ('difficult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Difficult')),
            ],
        ),
    ]
