# Generated by Django 3.0.8 on 2020-07-20 13:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=50)),
                ('incorrect_answer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), size=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Category')),
                ('difficult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Difficult')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Type')),
            ],
        ),
    ]
