# Generated by Django 3.0.8 on 2020-07-20 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_difficult_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='incorrect_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
